using System.ComponentModel.DataAnnotations;
using Microsoft.EntityFrameworkCore;

namespace ProCargo.Api.Data.Entities;

/// <summary>
/// A customer's request to move goods. Table: Bookings.
/// </summary>
public class Booking
{
    public long BookingId { get; set; }

    // generated by the database sequence
    public string BookingNumber { get; set; } = null!;

    public long CustomerId { get; set; }

    public Customer Customer { get; set; } = null!;

    public string PickupAddressText { get; set; } = "";

    public int? PickupCityId { get; set; }

    public City? PickupCity { get; set; }

    [Precision(9, 6)]
    public decimal? PickupLatitude { get; set; }

    [Precision(9, 6)]
    public decimal? PickupLongitude { get; set; }

    public string? PickupContactName { get; set; }

    public string? PickupContactPhone { get; set; }

    public string DropAddressText { get; set; } = "";

    public int? DropCityId { get; set; }

    public City? DropCity { get; set; }

    [Precision(9, 6)]
    public decimal? DropLatitude { get; set; }

    [Precision(9, 6)]
    public decimal? DropLongitude { get; set; }

    public string? DropContactName { get; set; }

    public string? DropContactPhone { get; set; }

    public int GoodsCategoryId { get; set; }

    public GoodsCategory GoodsCategory { get; set; } = null!;

    public string GoodsDescription { get; set; } = "";

    public int WeightKg { get; set; }

    [Precision(14, 2)]
    public decimal? GoodsValue { get; set; }

    public int VehicleTypeId { get; set; }

    public VehicleType VehicleType { get; set; } = null!;

    public DateOnly PickupDate { get; set; }

    public string? PickupSlot { get; set; }

    public string? SpecialInstructions { get; set; }

    // QuotePending | Quoted | Confirmed | Assigned | InTransit | Delivered | Completed | Cancelled
    public string Status { get; set; } = "QuotePending";

    public string? CancelledReason { get; set; }

    public long? CancelledBy { get; set; }

    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

    public DateTime? UpdatedAt { get; set; }

    [Timestamp]
    public byte[] RowVersion { get; set; } = Array.Empty<byte>();

    public List<Quote> Quotes { get; set; } = new();
}
