using System.ComponentModel.DataAnnotations;
using Microsoft.EntityFrameworkCore;

namespace ProCargo.Api.Data.Entities;

/// <summary>
/// The actual journey: one truck and one driver carrying one booking. Table: Trips.
/// </summary>
public class Trip
{
    public long TripId { get; set; }

    // generated by the database sequence
    public string TripNumber { get; set; } = null!;

    public long BookingId { get; set; }

    public Booking Booking { get; set; } = null!;

    public long OwnerId { get; set; }

    public Owner Owner { get; set; } = null!;

    public long VehicleId { get; set; }

    public Vehicle Vehicle { get; set; } = null!;

    public long DriverId { get; set; }

    public Driver Driver { get; set; } = null!;

    // Assigned | EnRouteToPickup | AtPickup | Loaded | InTransit | AtDestination | Delivered | Completed | Cancelled
    public string Status { get; set; } = "Assigned";

    // encrypted; shown only to the booking's customer
    public string? PickupOtpProtected { get; set; }

    public string? DeliveryOtpProtected { get; set; }

    public string? EwayBillNumber { get; set; }

    [Precision(8, 1)]
    public decimal? PlannedDistanceKm { get; set; }

    [Precision(8, 1)]
    public decimal? ActualDistanceKm { get; set; }

    public DateTime? ReachedPickupAt { get; set; }

    public DateTime? LoadedAt { get; set; }

    public DateTime? StartedAt { get; set; }

    public DateTime? ReachedDropAt { get; set; }

    public DateTime? DeliveredAt { get; set; }

    public long? PodApprovedBy { get; set; }

    public DateTime? PodApprovedAt { get; set; }

    [Precision(12, 2)]
    public decimal OwnerPayout { get; set; }

    [Precision(12, 2)]
    public decimal? DriverPay { get; set; }

    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

    public DateTime? UpdatedAt { get; set; }

    [Timestamp]
    public byte[] RowVersion { get; set; } = Array.Empty<byte>();

    public List<TripEvent> Events { get; set; } = new();
}
